version: "2"
networks:
  reverseproxy:
    external: true
services:
  nginx:
    image: nginx:latest
    container_name: reverseproxy
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./sites-enabled/:/etc/nginx/sites-enabled/:ro
      - ./includes/:/etc/nginx/includes/:ro
      - ./ssl/:/etc/nginx/ssl/:ro

      - ./logs/:/var/log/nginx/
      - ./cache/:/etc/nginx/cache/
    ports:
      - 80:80
      - 443:443
    networks:
      - reverseproxy